f-strings, line shortening, whitespace cleanup
Voxter256/Secret-Santa-Bot pull request #4
Opened 2020-05-27 02:17 UTC by ainen

I've converted all ".format" to f-strings, shortened some lines, and cleaned up some whitespace

2020-05-29 12:01 UTC, Voxter256 requested changes
Thank you so much for all of the fixes! They look great! A couple of minor requests but I'll approve the pull after that!

2020-05-29 12:01 UTC, Voxter256 commented on bot/models/BlockedLinks.py
> +        'blocked_link'), foreign_keys=blocked_id)
I like the shortened line lengths! It feels weird to me to split the line not on one of the Column/relationship parameters, but inside the Foreign Key / backref functions inside those parameters.

They are long enough that It makes sense to just have a new line for each parameter.

ex: 
```
Column(
    Integer,
    ForeignKey('participants.id'),
    index=True,
    nullable=True
)
```

2020-05-29 12:01 UTC, Voxter256 commented on bot/models/Link.py
> +        'participants.id'), index=True, default=None)
Same as above; would prefer split before or after ForeignKey, not inside

2020-05-29 12:01 UTC, Voxter256 commented on bot/models/Link.py
> +        'link_receiver'), foreign_keys=receiver_id)
Same as above; would prefer split before or after backref, not inside

2020-06-01 14:24 UTC, ainen commented
I pushed the formatting changes to my fork

2020-06-08 12:42 UTC, Voxter256 approved these changes

2020-06-08 12:42 UTC, merged